"""Declarative base and shared column conventions."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so Alembic emits stable, predictable constraint
# names. Without it, autogenerated migrations produce anonymous constraints
# that cannot reliably be dropped by a later downgrade.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKey:
    """Client-generated UUID primary key.

    Generated in Python rather than by the database so a row's identity is
    known before it is flushed -- the ingest pipeline needs to reference a
    document's id while assembling its child records.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampedAt:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


def status_enum(name: str) -> Enum:
    """A pending/ready/failed column, enforced by a CHECK constraint.

    ``name`` must be unique *within a table*: the naming convention renders
    constraints as ``ck_<table>_<enum name>``, so two columns in one table
    sharing an enum name would collide on the constraint name.

    ``create_constraint=True`` is not the default -- SQLAlchemy flipped it to
    False in 1.4 -- and omitting it yields a bare VARCHAR that accepts any
    string while still reading like an enum.
    """
    return Enum(
        "pending",
        "ready",
        "failed",
        name=name,
        native_enum=False,
        create_constraint=True,
    )
